version: '3.3'

services:
  api:
    container_name: omni_nlu
    build: .
    image: base_image
    restart: always
    user: root
    volumes:
      - ./src:/usr/omni_nlu_api/src
    working_dir: /usr/omni_nlu_api
    environment:
      - ELASTICSEARCH_HOST=192.168.0.186
    ports:
      - 5000:5000

  bash:
    image: base_image
    user: root
    volumes:
      - ./src:/usr/omni_nlu_api/src
    working_dir: /usr/omni_nlu_api/src
    entrypoint: /bin/sh
    environment:
        - ELASTICSEARCH_HOST=192.168.0.186

  jupyter:
      image: base_image
      user: root
      volumes:
        - ./jupyter_notebooks:/usr/omni_nlu_api/jupyter_notebooks
      working_dir: /usr/omni_nlu_api/
      environment:
        - ELASTICSEARCH_HOST=192.168.0.186
        - API_KEY=nA36HqlqQkQSDf0EywIeYGPl0qI_nNvLqvBUI_zhhUmR
        - SERVICE_URL=https://api.us-south.assistant.watson.cloud.ibm.com/instances/12c017ac-1bb4-4364-8493-9cc9ba98aa26
        - ASSISTANT_ID=fb636035-ab5f-42f4-9e15-7217458a754f
      command: "jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root --no-browser"
      ports:
        - 8888:8888