version: '3.3'

services:
  api:
    container_name: omni_nlu
    build: .
    image: base_image
    restart: always
    user: root
    volumes:
      - ./src:/usr/omni_nlu_api/src
    working_dir: /usr/omni_nlu_api
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    ports:
      - 5000:5000

  bash:
    image: base_image
    user: root
    volumes:
      - ./src:/usr/omni_nlu_api/src
    working_dir: /usr/omni_nlu_api/src
    entrypoint: /bin/sh
    environment:
        - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}

  jupyter:
      image: base_image
      user: root
      volumes:
        - ./jupyter_notebooks:/usr/omni_nlu_api/jupyter_notebooks
      working_dir: /usr/omni_nlu_api/
      environment:
        - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
        - API_KEY=${API_KEY}
        - SERVICE_URL=${SERVICE_URL}
        - ASSISTANT_ID=${ASSISTANT_ID}
      command: "jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root --no-browser"
      ports:
        - 8888:8888