version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: kibana:7.10.1
    restart: always
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  api:
    container_name: omni_nlp_api
    build: .
    image: base_image
    restart: always
    user: root
    volumes:
      - ./src:/usr/omni_nlu_api/src
    working_dir: /usr/omni_nlu_api
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch

  bash:
    image: base_image
    user: root
    volumes:
      - ./src:/usr/omni_nlu_api/src
    working_dir: /usr/omni_nlu_api/src
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    entrypoint: /bin/sh

  python3:
    image: base_image
    user: root
    volumes:
      - ./src:/usr/omni_nlu_api/src
    working_dir: /usr/omni_nlu_api/src
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    command: "python3"

  # jupyter:
  #     image: base_image
  #     user: root
  #     volumes:
  #       - ./jupyter_notebooks:/usr/omni_nlu_api/jupyter_notebooks
  #     working_dir: /usr/omni_nlu_api
  #     environment:
  #     - ELASTICSEARCH_HOST=elasticsearch
  #     command: "jupyter lab --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root --no-browser"
  #     ports:
  #       - 8889:8889

  # test:
  #   image: base_image
  #   user: root
  #   volumes:
  #     - .:/usr/omni_nlu_api
  #   environment:
  #     - ELASTICSEARCH_HOST=omni_nlp_elasticsearch
  #   depends_on:
  #     - elasticsearch
  #   working_dir: /usr/omni_nlu_api
  #   command: "pytest --verbose"

volumes:
  elasticsearch-data-volume:
    driver: local
